### ISSUE TITLE
long_names in bgc_param.nc don't match Hayashida et al 2020

### ISSUE THREAD

**Issue by aekiss** [hakaseh/input_om2-bgc#11]
@hakaseh I've added long_names and units to `bgc_param.nc`, based on my understanding of [Ziehn et al 2020](https://doi.org/10.1071/ES19035) table 2.

There are two inconsistencies with the table in the supplement to [Hayashida et al (2020)](https://doi-org.virtual.anu.edu.au/10.1111/gcb.15255) (H2020): 

1. H2020 say `muedbio_sed` is the detritus remineralisation rate for >=180m, but I've given it the long_name "Detritus remineralisation rate in sediments", as this seems consistent with the code (which hard-wires `muedbio`/2 as the detritus remineralisation rate for >=180m). I've given `muedbio` the long_name "Detritus remineralisation rate for <180 m; value for >=180m is half of this".
2. H2020 say `muecaco3_sed` is the caco3 remineralisation rate, but I've given `muecaco3_sed` the long_name "CaCO3 remineralisation rate in sediments", and instead given `muecaco3` the long_name "CaCO3 remineralisation rate"

Have I got this right? (i.e. are 1. and 2. wrong in H2020?)

**Comment by hakaseh** [comment]
@aekiss sorry for the late reply. yes, you are correct for both 1 and 2. (ref: https://github.com/COSIMA/input_om2-bgc/issues/3)
