### ISSUE TITLE
Make script generate 01deg-cycle4 inputs too?

### ISSUE THREAD

**Issue by aekiss** [hakaseh/input_om2-bgc#5]
For the sake of documentation, it would be good to put the code used to generate the 01deg-cycle4 inputs into `interpolate_to_access-om2.ipynb`.
see https://github.com/COSIMA/1deg_jra55_iaf/pull/11#issuecomment-919605569 and https://github.com/COSIMA/1deg_jra55_iaf/pull/11#issuecomment-921382899

**Comment by hakaseh** [comment]
sure. i can do that and update `master`.

**Comment by hakaseh** [comment]
i pushed `main` to allow generation of 01deg-cycle4 inputs. The only difference from `master+bgc` is the initial condition file `csiro_bgc.res.nc`. In the code, i added a variable called `my_choice` which can be set to either `master+bgc`, `01deg_jra55v140_iaf_cycle4`, or `iamip2`, depending on for which initial conditions the user wants to generate.

**Comment by aekiss** [comment]
great, thanks!
